Adds documentation and format files
Art-Ev/qaequilibrae pull request #2
Opened 2024-05-24 19:33 UTC by r-akemii

In this PR I would like to add a documentation module in docs for the processing providers you created.

I also propose renaming the module files to be more pythonic and removing the _icon.png_ file, once we can use the one in the qaequilibrae folder.

There are also proposals to modify some of the new translatable strings. The less new translatable strings we have, the best. Thus, I propose renaming the provider menu to match the one in qaequilibrae, and the tool names to be less verbose. What drove me to this set of modifications is thinking that today we're frequently updating the translations, but in the future, there can exist too many untranslated words for lack of maintenance.

2024-05-24 19:34 UTC, r-akemii commented
@Art-Ev if you want to talk to me about any of these modifications, just let me know!

2024-06-13 08:19 UTC, Art-Ev requested changes
Seems good to mee, juste some changes we need to make to keep control on menu order in qgis interface (proposals in review comments)

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/Add_connectors.py
> +        return self.tr("Model Building")
To keep menus in order we better use "1-Model Building"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/Add_connectors.py
> +        return self.tr("Model Building")
Proposal : "1-Model Building"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/assign_from_yaml.py
> +        return self.tr("Paths and assignment")
"3-Paths and assignment"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/assign_from_yaml.py
> +        return self.tr("Paths and assignment")
"3-Paths and assignment"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/export_matrix.py
> +        return self.tr("Data")
"2-Data"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/export_matrix.py
> +        return self.tr("Data")
"2-Data"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/matrix_from_layer.py
> +        return self.tr("Data")
"2-Data"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/matrix_from_layer.py
> +        return self.tr("Data")
"2-Data"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/project_from_layers.py
> +        return self.tr("Model Building")
"1-Model Building"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/project_from_layers.py
> +        return self.tr("Model Building")
"1-Model Building"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/renumber_from_centroids.py
> +        return self.tr("Model Building")
"1-Model Building"

2024-06-13 08:19 UTC, Art-Ev commented on qaequilibrae/modules/processing_provider/renumber_from_centroids.py
> +        return self.tr("Model Building")
"1-Model Building"

2024-06-17 16:11 UTC, closed without merging